# Generated by Django 6.0.1 on 2026-04-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roadmap',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
