# Generated by Django 6.0.1 on 2026-04-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
