# Generated by Django 6.0.1 on 2026-04-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_chatbot_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
