# Generated by Django 6.0.1 on 2026-04-02

import datetime

import django.db.models.deletion
from django.db import migrations, models


def _extract_age(onboarding_data):
    if not onboarding_data:
        return 0

    explicit_age = onboarding_data.get('age')
    if explicit_age not in (None, ''):
        try:
            return max(int(explicit_age), 0)
        except (TypeError, ValueError):
            pass

    birth_date = onboarding_data.get('birth_date')
    if not birth_date:
        return 0

    try:
        parsed = datetime.date.fromisoformat(str(birth_date))
    except (TypeError, ValueError):
        return 0

    today = datetime.date.today()
    return max(
        today.year - parsed.year - ((today.month, today.day) < (parsed.month, parsed.day)),
        0,
    )


def move_user_data_to_profile(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')

    for user in User.objects.all():
        onboarding_data = dict(user.onboarding_data or {})
        first_name = str(onboarding_data.pop('name', user.first_name or '') or '').strip()
        last_name = str(onboarding_data.pop('surname', user.last_name or '') or '').strip()
        age = _extract_age(onboarding_data)

        user.first_name = first_name
        user.last_name = last_name
        user.age = age
        user.save(update_fields=['first_name', 'last_name', 'age'])

        profile, _ = UserProfile.objects.update_or_create(
            user=user,
            defaults={
                'provider': user.provider,
                'created_at': user.created_at,
                'onboarding_completed': user.onboarding_completed,
                'onboarding_data': onboarding_data,
                'onboarding_progress': user.onboarding_progress,
                'chat_history': user.chat_history,
                'iq_score': user.iq_score,
                'psychological_profile': user.psychological_profile,
                'roadmap': user.roadmap,
                'weekly_plan': user.weekly_plan,
                'chatbot_history': user.chatbot_history,
                'daily_plan': user.daily_plan,
            },
        )
        UserProfile.objects.filter(pk=profile.pk).update(created_at=user.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studytrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='email', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_data', models.JSONField(blank=True, null=True)),
                ('onboarding_progress', models.TextField(blank=True, null=True)),
                ('chat_history', models.JSONField(blank=True, null=True)),
                ('iq_score', models.IntegerField(default=0)),
                ('psychological_profile', models.JSONField(blank=True, null=True)),
                ('roadmap', models.JSONField(blank=True, null=True)),
                ('weekly_plan', models.JSONField(blank=True, null=True)),
                ('chatbot_history', models.JSONField(blank=True, null=True)),
                ('daily_plan', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.user')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.RunPython(move_user_data_to_profile, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_progress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chat_history',
        ),
        migrations.RemoveField(
            model_name='user',
            name='iq_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='psychological_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roadmap',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekly_plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chatbot_history',
        ),
        migrations.RemoveField(
            model_name='user',
            name='daily_plan',
        ),
    ]
