# Generated by Django 6.0.1 on 2026-04-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_weekly_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chatbot_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
