# Generated by Django 6.0.1 on 2026-04-02 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_daily_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('daily_plan', models.JSONField(blank=True, null=True)),
                ('weekly_plan', models.JSONField(blank=True, null=True)),
                ('roadmap', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_tracks',
                'ordering': ['created_at'],
            },
        ),
    ]
