# Generated by Django 6.0.1 on 2026-04-02

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studytrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='email', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_data', models.JSONField(blank=True, null=True)),
                ('onboarding_progress', models.TextField(blank=True, null=True)),
                ('chat_history', models.JSONField(blank=True, null=True)),
                ('iq_score', models.IntegerField(default=0)),
                ('psychological_profile', models.JSONField(blank=True, null=True)),
                ('roadmap', models.JSONField(blank=True, null=True)),
                ('weekly_plan', models.JSONField(blank=True, null=True)),
                ('chatbot_history', models.JSONField(blank=True, null=True)),
                ('daily_plan', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.user')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_progress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chat_history',
        ),
        migrations.RemoveField(
            model_name='user',
            name='iq_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='psychological_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roadmap',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekly_plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chatbot_history',
        ),
        migrations.RemoveField(
            model_name='user',
            name='daily_plan',
        ),
    ]
